[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "httpx>=0.28.1",
    "mistralai>=1.10.1",
    "pydantic-settings>=2.12.0",
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "uvicorn>=0.40.0",
]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "C4", "UP"]
ignore = []

[tool.pyright]
include = ["."]
exclude = ["**/node_modules", "**/__pycache__", ".venv"]
pythonVersion = "3.13"
typeCheckingMode = "basic"
